name: clang-tidy

on:
  push:
    branches:
      - develop
      - master
      - main
  pull_request_target:
    branches:
      - "*"

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup init_script
      shell: bash
      run: |
        cat > init_script.sh << 'EOF'
        #!/bin/bash
        # Input args provided by StaticAnalysis action
        root_dir=${1}
        build_dir=${2}
        echo "Hello from init script! root_dir=${root_dir}, build_dir=${build_dir}"

        # enable latest Mesa/Vulkan drivers
        add-apt-repository -y ppa:oibaf/graphics-drivers
        apt update && apt upgrade -y

        # install Vulkan support on Ubuntu
        apt install -y libvulkan1 mesa-vulkan-drivers vulkan-tools
        EOF
        chmod +x init_script.sh

    - name: Run Static Analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        language: c++
        exclude_dir: lib
        use_cmake: true
        apt_pckgs: software-properties-common libglu1-mesa-dev freeglut3-dev mesa-common-dev
        init_script: init_script.sh
